language: python

python:
    - 2.7
    - 3.5
    - 3.6

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

env:
    global:

        # The following versions are the 'default' for tests, unless
        # overridden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=stable
        - SETUP_CMD='test'
        - MAIN_CMD='python setup.py'
        - PIP_DEPENDENCIES=''
        - CONDA_DEPENDENCIES='Cython shapely pytest-arraydiff'
        - CONDA_CHANNELS='astropy'
        - SETUP_XVFB=True
        - ASTROPY_USE_SYSTEM_PYTEST=1

    matrix:
        # Make sure that egg_info works without dependencies
        - SETUP_CMD='egg_info'

matrix:
    include:

        # Do a coverage test in Python 3.
        - python: 3.7
          dist: xenial
          sudo: true
          env: SETUP_CMD='test --coverage'
               CONDA_CHANNELS='conda-forge astropy'
        # Check for sphinx doc build warnings - we do this first because it
        # may run for a long time
        - python: 2.7
          env: SETUP_CMD='build_docs -w'
        - python: 3.7
          dist: xenial
          sudo: true
          env: SETUP_CMD='build_docs -w'
               CONDA_CHANNELS='conda-forge astropy'
        # Do a test without the optional dependencies
        - python: 3.7
          dist: xenial
          sudo: true
          env: SETUP_CMD='test'
               CONDA_DEPENDENCIES='Cython pytest-arraydiff'


        # Try Astropy development version
        - python: 3.7
          dist: xenial
          sudo: true
          env: ASTROPY_VERSION=development
               CONDA_CHANNELS='conda-forge astropy'

        # Try older numpy versions
        - python: 3.6
          env: NUMPY_VERSION=1.11
        - python: 3.5
          env: NUMPY_VERSION=1.10

        # Try numpy pre-release
        - python: 3.7
          dist: xenial
          sudo: true
          env: NUMPY_VERSION=prerelease

        # Do a PEP8 test with pycodestyle
        - python: 3.7
          dist: xenial
          sudo: true
          env: MAIN_CMD='pycodestyle regions --count' SETUP_CMD=''

install:

    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh

script:
   - $MAIN_CMD $SETUP_CMD

after_success:
    - if [[ $SETUP_CMD == 'test --coverage' ]]; then coveralls --rcfile='regions/tests/coveragerc'; fi
